# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 03:45
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_name', models.CharField(max_length=100, unique=True)),
                ('quote_date_created', models.DateTimeField(auto_now_add=True)),
                ('quote_last_modified', models.DateTimeField(auto_now=True)),
                ('quote_due_date', models.DateField()),
                ('quote_copies', models.IntegerField()),
                ('quote_product_name', models.CharField(max_length=100)),
                ('quote_dimention_width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quote_dimention_length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quote_printing_bleed', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('quote_printing_sides', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(2)])),
                ('quote_printing_colors_front', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(4)])),
                ('quote_printing_colors_back', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(4)])),
                ('quote_is_authorized', models.BooleanField(default=False)),
                ('quote_is_approved', models.BooleanField(default=True)),
                ('quote_total_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('quote_imposing_per_sheet', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
