# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0003_auto_20160118_0752'),
        ('ventas', '0002_auto_20160118_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='materials',
            field=models.ManyToManyField(to='recursos.Material'),
        ),
        migrations.AddField(
            model_name='quote',
            name='paper',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recursos.Paper'),
            preserve_default=False,
        ),
    ]
