# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20160117_0016'),
        ('recursos', '0003_auto_20160118_0752'),
        ('ventas', '0003_auto_20160118_0752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote_Finishing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateTimeField()),
                ('date_finished', models.DateTimeField()),
                ('finishing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.Finishing')),
            ],
        ),
        migrations.AddField(
            model_name='quote',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='personal.Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='executive',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='personal.Executive'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote_finishing',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.Quote'),
        ),
        migrations.AddField(
            model_name='quote',
            name='finishings',
            field=models.ManyToManyField(through='ventas.Quote_Finishing', to='recursos.Finishing'),
        ),
    ]
