# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-23 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_auto_20160518_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_total_sheets',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
