# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-24 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_quote_quote_total_sheets'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quire',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_copies',
            field=models.PositiveIntegerField(),
        ),
    ]
