# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-24 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_auto_20160524_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='quire',
            new_name='quires',
        ),
    ]
