# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-30 22:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import ventas.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0009_auto_20160524_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_dimention_length',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[ventas.validators.validate_dimentions]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_dimention_width',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[ventas.validators.validate_dimentions]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_due_date',
            field=models.DateField(validators=[ventas.validators.validate_due_date]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_printing_colors_back',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_printing_colors_front',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_printing_sides',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)]),
        ),
    ]
