# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-31 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_auto_20160530_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='quires',
            new_name='quote_quires',
        ),
    ]
