# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-31 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0011_auto_20160531_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date_created', models.DateTimeField(auto_now_add=True)),
                ('order_packaging_instructions', models.TextField(null=True)),
                ('order_delivery_address', models.CharField(max_length=255)),
                ('order_notes', models.TextField(null=True)),
                ('order_is_started', models.BooleanField(default=False)),
                ('order_datetime_started', models.DateTimeField(null=True)),
                ('order_is_finished', models.BooleanField(default=False)),
                ('order_datetime_finished', models.DateTimeField(null=True)),
                ('authorized_quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ventas.AuthorizedQuote')),
            ],
        ),
    ]
