# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-07 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorizedquote',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='order',
            name='authorized_quote',
        ),
        migrations.AddField(
            model_name='order',
            name='quote',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ventas.Quote'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_datetime_authorized',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='AuthorizedQuote',
        ),
    ]
