# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-10 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_auto_20160607_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote_finishing',
            old_name='date_finished',
            new_name='quote_finishing_datetime_finished',
        ),
        migrations.RenameField(
            model_name='quote_finishing',
            old_name='date_started',
            new_name='quote_finishing_datetime_started',
        ),
        migrations.AddField(
            model_name='quote_finishing',
            name='quote_finishing_is_finished',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quote_finishing',
            name='quote_finishing_is_started',
            field=models.BooleanField(default=False),
        ),
    ]
