# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-10 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_auto_20160610_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote_finishing',
            name='quote_finishing_is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
