# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-14 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_op_number', models.CharField(max_length=10)),
                ('order_client', models.CharField(max_length=255)),
                ('order_description', models.CharField(max_length=100)),
                ('order_machine', models.CharField(max_length=50)),
                ('order_quantity', models.PositiveIntegerField()),
                ('order_total_sheets', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order_Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_process_is_started', models.BooleanField(default=False)),
                ('order_process_datetime_started', models.DateTimeField(null=True)),
                ('order_process_is_finished', models.BooleanField(default=False)),
                ('order_process_datetime_finished', models.DateTimeField(null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_produccion.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='order_process',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_produccion.Process'),
        ),
        migrations.AddField(
            model_name='order',
            name='processes',
            field=models.ManyToManyField(through='control_produccion.Order_Process', to='control_produccion.Process'),
        ),
    ]
