# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-14 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_produccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_op_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
