# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-16 18:33
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('control_produccion', '0003_order_order_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_due_date',
            field=models.DateTimeField(default=timezone.now()),
        ),
    ]
