# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-22 17:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control_produccion', '0004_order_order_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_process',
            name='order_process_user_finished',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_processes_finished', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order_process',
            name='order_process_user_started',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_processes_started', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_due_date',
            field=models.DateTimeField(),
        ),
    ]
