# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-23 00:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('control_produccion', '0005_auto_20160622_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date_created',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 23, 0, 12, 26, 682093, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
