# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-23 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_produccion', '0006_order_order_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_process',
            name='order_process_datetime_pause_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order_process',
            name='order_process_is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order_process',
            name='order_process_seconds_paused',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
