# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, unique=True)),
                ('client_receipt_name', models.CharField(max_length=255)),
                ('client_receipt_address', models.CharField(max_length=255)),
                ('client_nit', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Executive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executive_comssn', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=100)),
                ('person_lastname', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='executive',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Person'),
        ),
    ]
