# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='executive',
            old_name='person_id',
            new_name='person',
        ),
    ]
