# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 00:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20160116_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executive',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Person', unique=True),
        ),
    ]
