# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20160118_0356'),
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishing',
            name='quote',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ventas.Quote'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='quote',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ventas.Quote'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='quote',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='ventas.Quote'),
            preserve_default=False,
        ),
    ]
